apiVersion: apps/v1
kind: Deployment
metadata:
  name: asrar1990
spec:
  replicas: 2
  selector:
    matchLabels:
      app: asrar1990
  template:
    metadata:
      labels:
        app: asrar1990
    spec:
      containers:
      - name: asrar1990
        image: crappsample.azurecr.io/asrar1990/asrar1990:#{Build.BuildId}#
        ports:
        - containerPort: 5000
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: my-python-app-svc
spec:
  selector:
    app: my-python-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
